spring:
  datasource:
    username: test
    password: test
    url: jdbc:postgresql://postgresql.medofa.bedigital.vn:5432/ktx-api
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect